<template lang="html">
  <div v-if="loading" class="loading-page">
    <div class="loadingio-spinner-spinner-8xsbjfqucq9">
      <div class="ldio-dpo4etqty9">
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
        <div></div>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  data: () => ({
    loading: false,
  }),
  methods: {
    start() {
      this.loading = true
    },
    finish() {
      this.loading = false
    },
  },
}
</script>

<style scoped>
.loading-page {
  position: fixed;
  top: 0;
  left: 0;
  width: 100%;
  height: 100%;
  background: #f1f2f3;
  z-index: 100;
  display: flex;
  justify-content: center;
  align-items: center;
}
@keyframes ldio-dpo4etqty9 {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-dpo4etqty9 div {
  left: 94px;
  top: 48px;
  position: absolute;
  animation: ldio-dpo4etqty9 linear 1s infinite;
  background: #004d73;
  width: 12px;
  height: 24px;
  border-radius: 6px / 12px;
  transform-origin: 6px 52px;
}
.ldio-dpo4etqty9 div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #004d73;
}
.ldio-dpo4etqty9 div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #004d73;
}
.loadingio-spinner-spinner-8xsbjfqucq9 {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #f1f2f3;
}
.ldio-dpo4etqty9 {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-dpo4etqty9 div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
